security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        database_users:
            entity:
                class: App:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            guard:
                authenticator:
                    - App\Security\LoginAuthenticator
                    - App\Security\GoogleAuthenticator
                    - App\Security\FacebookAuthenticator

                entry_point: App\Security\LoginAuthenticator

            logout:
                path: /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user,  roles: ROLE_USER }